### PR TITLE
C407 - unnecessary list comprehension - 'x' can take a generator

### LINKED ISSUE #5: sum of list comprehension better as sum of generator
e.g. `sum([foo.bar for foo in get_foos()])` -> `sum(foo for foo in get_foos())`

Probably extensible to other callables like `any`, `all`, `sorted`, etc.

### PR DESCRIPTION
**Pull request by adamchainz**
Fixes #5.

### CODE REVIEW

**Comment by jiffyclub** [comment]
This would be great to have included, would you like any help getting this done?

**Comment by adamchainz** [comment]
I haven't taken the time to list all the builtins that can take generators, if you can find this list (maybe there's an automated way?) then we'd be closer

**Comment by jiffyclub** [comment]
I'd suggest `all`, `any`, `frozenset`, `max`, `min`, `sorted`, `sum`, and `tuple`. Possibly also `filter`, `map`, and `enumerate`. (I made that list by going [here](https://docs.python.org/3/library/functions.html) and searching for any function that took an `iterable` as an argument.)

**Comment by jiffyclub** [comment]
There are other things in the standard library that can take iterables (like the things in `itertools` and `statistics`), but I don't know if it's worth tracking down everything, even covering the most common cases would be useful.

**Comment by adamchainz** [comment]
I think we'll go for the builtins first since they tend to not be shadowed as names. Detecting the others can be painful, since code can create functions with the same names with no risk of shadowing..

**Comment by adamchainz** [comment]
:up:dated , look good to you @jiffyclub ?

**Comment by jiffyclub** [comment]
Looks good, thanks!

**Comment by adamchainz** [comment]
Now on pip at 1.2.1 : https://pypi.python.org/pypi/flake8-comprehensions

**Pull request merged**
