### PR TITLE
Add C417 - Unnecessary use of `map`

### LINKED ISSUE #405: Convert `map(lambda x: expression, iterable)` to `(expression for x in iterable)`
### Description

`map(f, iterable)` has great performance when `f` is a built-in function, and it makes sense if your function already has a name. But if you need to introduce a lambda, it's better (i.e., more readable and faster) to use a generator expression -- no function calls needed.

Good:
```
for y in map(my_function_that_already_exists, it):
    ...
ys = list(map(my_function_that_already_exists, it))
ys = set(map(my_function_that_already_exists, it))
etc.
```

Suggestions:
```
# Bad:
map(lambda x: x**2, iterable)
# change to:
(x**2 for x in iterable)

# Bad:
list(map(lambda x: x.attr, iterable))
# change to:
[x.attr for x in iterable]
# OR change to:
y = list(map(operator.attrgetter("attr"), iterable))

# Bad:
z = map(lambda x: f(x), iterable)
# change to:
z = map(f, iterable)
```

Here are some perf numbers (`deque(..., maxlen=0)` is a fast way to consume an iterable):

```
PS C:\Users\sween> py -3.8 -m pyperf timeit -s "from collections import deque" "deque(map(lambda x: -x, range(1_000_000)), maxlen=0)"
Mean +- std dev: 85.7 ms +- 1.7 ms

PS C:\Users\sween> py -3.8 -m pyperf timeit -s "from collections import deque" "deque((-x for x in range(1_000_000)), maxlen=0)"

Mean +- std dev: 63.1 ms +- 2.9 ms
```

Similar things hold for `filter()`.

### PR DESCRIPTION
**Pull request by tusharsadhwani**
Resolves #405

### CODE REVIEW

**Comment by tusharsadhwani** [comment]
Can I also add set comprehensions for `set(map(...))`?

**Comment by adamchainz** [comment]
I think it makes sense - and `dict(map())` as well, if you could! They could also all be one error code with a templated message, IMO.

I haven't found time to review this properly but it looks good.

**Comment by tusharsadhwani** [comment]
@adamchainz Merged it all into C417, and added set and dict as well.

**Comment by sbrugman** [comment]
What is the status on this one?
(Would be neat to have C417 if [C418/C419](https://github.com/adamchainz/flake8-comprehensions/pull/427) are accepted)

**Comment by adamchainz** [comment]
Released in 3.10.0, thanks!

**Pull request merged**
