### PR TITLE
Add __slots__ to plugin class to reduce memory footprint

### PR DESCRIPTION
**Pull request by sondrelg**
Hi! 

First of all, thanks for creating this plugin! I've been using it for years now and it's great 👏

This PR is more of a question than a clear suggested improvement; I thought about raising an issue to discuss it, but a PR seemed more actionable in case you agree with the rationale.

## Changes

So the PR simply defines `__slots__` on the plugin class, to pre-declare the class attributes we expect and in turn, make it a *little bit* more performant.

I did some memory profiling using [memory_profiler](https://github.com/pythonprofilers/memory_profiler) and from what I can tell, this reduces the memory footprint of the plugin class by 15-20%. I also tested using `sys.getsizeof` and found basically the same results there.

The drawback of declaring `__slots__`, is of course that it prevents you from setting new instance variables during runtime, but as far as I can tell (and I could be wrong), flake8 never does this. I don't know of any other flake8-plugins that have this declared, so there could be a reason why this is a bad idea, but they are not clear to me, and the [test-suite](https://github.com/sondrelg/flake8-comprehensions/actions) seems to have passed 🎉

<br>Curious to see what your take on this is 😌  

Thanks again 👏

### CODE REVIEW

**Comment by adamchainz** [comment]
Thanks for using the plugin and trying to optimize it.

>  did some memory profiling using memory_profiler and from what I can tell, this reduces the memory footprint of the plugin class by 15-20%. I also tested using sys.getsizeof and found basically the same results there.

What's the actual number? And did you measure for a change in runtime? If anything, I'd expect an *increase* in runtime since flake8 normally runs on a handful of files, so a handful of instances will be created, whilst using `__slots__` imposes an extra class definition cost.

If you're looking to optimize the flake8 runtime I can imagine there are much richer veins of optimization to pursue. Try profiling a whole run and seeing what happens. Micro optimization PR's like this often don't pay for even the time writing them.

**Comment by sondrelg** [comment]
Wrote a quick script to instantiate and run an arbitrary ast tree (lots of prints 🤷‍♂️), to check the runtime.

I've assumed the ast objects wouldn't matter since everything else is held constant except the `__slots__`.

**Test script**
```python
import ast
from timeit import timeit

from src.flake8_comprehensions import ComprehensionChecker as no_slots
from src.flake8_comprehensions2 import ComprehensionChecker as with_slots

example_code = "".join(f'print("{i}")\n' for i in range(10000))

tree = example_code

for n in range(1, 9):
    number_of_iterations = 10**n

    no_slots_runtime = timeit(lambda: no_slots(ast.parse).run(), number=number_of_iterations)
    with_slots_runtime = timeit(lambda: with_slots(ast.parse).run(), number=number_of_iterations)

    print(f'\n\nn={number_of_iterations}:\nNo slots: {no_slots_runtime}\nWith slots: {with_slots_runtime}')
    print(f'With slots was {round(100*((no_slots_runtime - with_slots_runtime)/with_slots_runtime),2)}% faster')
```

**Output**
```
n=10:
No slots: 1.120699999999919e-05
With slots: 8.31399999999538e-06
With slots was 34.8% faster


n=100:
No slots: 6.546200000000224e-05
With slots: 5.238700000000096e-05
With slots was 24.96% faster


n=1000:
No slots: 0.0006326690000000024
With slots: 0.0005133370000000026
With slots was 23.25% faster


n=10000:
No slots: 0.00631502099999999
With slots: 0.0055627250000000045
With slots was 13.52% faster


n=100000:
No slots: 0.082363096
With slots: 0.058382287000000005
With slots was 41.08% faster


n=1000000:
No slots: 0.668564893
With slots: 0.568828884
With slots was 17.53% faster


n=10000000:
No slots: 6.7718321150000005
With slots: 5.965638953999999
With slots was 13.51% faster

n=100000000:
No slots: 67.52766287600001
With slots: 58.72048219599999
With slots was 15.0% faster
```

After running this a few times I have yet to see the results go the other way, so doesn't look too bad, but perhaps I've missed something.

Re flake8 normally running on a few files - I agree this doesn't really make a tangible difference if you're using flake8 with pre-commit or other similar tooling, but I bet the aggregate time spent running this flake8-hook per day is pretty high 🙂

I don't still have the memory profiling code from earlier, but can revisit it tomorrow if you want. Then again, if you're totally disinterested, feel free to close the PR as well - this was mostly a fun experiment 👏

**Comment by adamchainz** [comment]
I ran a much simpler benchmark in IPython trying to isolate the difference between no-slots and slots in a class and found no clear difference:

```
In [1]: class NoSlots:
   ...:     def __init__(self, obj):
   ...:         self.obj = obj
   ...:

In [2]: class Slots:
   ...:     __slots__ = ('obj',)
   ...:
   ...:     def __init__(self, obj):
   ...:         self.obj = obj
   ...:

In [3]: %timeit NoSlots(1)
170 ns ± 0.372 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [4]: %timeit Slots(1)
172 ns ± 0.514 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

I'm not sure if somehow your benchmark was affected by e.g. cached parsing between runs, etc. Your code also doesn't use the `tree` variable - I think you missed a call to `ast.parse()`?

I think you will also be affected by which Python version you're using. I'm testing with 3.9. Vanilla classes without `__slots__` have been repeatedly optimized as dicts have been refined. The [3.4 key-sharing optimization](https://www.python.org/dev/peps/pep-0412/), [Python 3.6 dict rewrite](https://docs.python.org/3/whatsnew/3.6.html) both optimized them, and [Python 3.9 vectorcall optimization](https://docs.python.org/3/whatsnew/3.9.html) have all reduced the cost of dicts, and therefore reduced the advantage of slots.

I think a more effective approach to optimizing flake8-comprehensions would be to profile the plugin with e.g. py-spy when run against a bunch of big files from a big codebase (e.g. Django) and see where the time is spent.

One idea: flake8-comprehensions uses many `isinstance` calls which can be quite slow, and since the ast has a predictable class hierarchy we can probably be replace them with `node.__class__ is ast.<Class>`.

Another idea: simple reordering of some conditionals to check cheap/uncommon things first on each node could yield a big improvement.

Anyway I hope you've enjoyed learning from this experiment and I've given you some things to think about.

**Comment by adamchainz** [comment]
I was just trying to investigate if `__slots__` really is no longer worth it on Python, and found actually my benchmark above was bad, and it actually does have some effect.

**Comment by sondrelg** [comment]
Your test ran differently for me

```
In [9]: class NoSlots: 
   ...:     def __init__(self, obj): 
   ...:         self.obj = obj 
   ...:                                                                                                                                                                                                       

In [10]: class Slots: 
    ...:     __slots__ = ('obj',) 
    ...:     def __init__(self, obj): 
    ...:         self.obj = obj 
    ...:                                                                                                                                                                                                      

In [11]: %timeit NoSlots(1)                                                                                                                                                                                   
242 ns ± 11.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [12]: %timeit Slots(1)                                                                                                                                                                                     
182 ns ± 3.8 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

# Run once more to be sure

In [13]: %timeit NoSlots(1)                                                                                                                                                                                   
245 ns ± 3.53 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [14]: %timeit Slots(1)                                                                                                                                                                                     
193 ns ± 11.7 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [16]: ((245+242) - (193+182)) / (245+242)                                                                                                                                                                  
Out[16]: 0.2299794661190965
```

I'm on 3.9.0 with Pyenv 🤔

**Comment by adamchainz** [comment]
Yes I repeated and got those same results. I must have made a mistake!

**Comment by sondrelg** [comment]
Happy days 😄

Thanks!

**Pull request merged**
