### PR TITLE
Simplify messages in tests

### PR DESCRIPTION
**Pull request by joaoe**
Hi.

I thought of sending in a patch, but though first I could make testing a bit easier.

The branch refactors the strings in the code logic into a reusable dict.
Then tests just reuse the dicts with messages to generate messages on the fly saving on a lot of copy past and hardcoded text.

If you don't want these changes, it's ok. At least I'll send a fix to make the tests work on Windows.

Thank you.

### CODE REVIEW

**Comment by joaoe** [comment]
`multilint` and `black` produce conflicting output.

**Comment by adamchainz** [comment]
Hi

Sorry I forgot to fully review this PR before diving into a fix for #212 . I read your message and thought you'd only refactored the tests 🤗

I'm afraid I'm not particularly interested in the test simplification as it stands. I think it makes the tests less explicit and a bit more dependent on the system-under-test, since you're pulling the messages back off the checker class. There's definitely opportunity to simplify though, possibly by actually parsing the lines in the underlying test helper, [pytest-flake8dir](https://github.com/adamchainz/pytest-flake8dir).

Also the extraction of `suffixes` - it doesn't seem to deduplicate any messaging, it was only to support the test simplification right?

As I said, the improvements to C407 were done in #214 , and expandeed to dict/set in #215.

The check for `functools.reduce`, as I wrote on #212, is not easy. Your current implementation only checks for users who do `import functools ; functools.reduce(...`  . Others will use `from functools import reduce ; reduce(...`. To be strictly accurate that it's `functools.reduce` being called and not some other `reduce` helper (idk there might be a common one out there), we'd need to check the names imported into the current scope, which is quite a lot of work. Hence why I didn't want to add that check (at least for now). Avoiding false positives is my first priority with linters, since too many false positives prevents users from using them.

Absolutely interested in a PR that fixes the tests on Windows. I can't see anything in this PR? Is it perhaps something for pytest-flake8dir?

Thanks,

Adam

**Comment by joaoe** [comment]
Hi.
1. I was going to do a fix for #212 myself but I though the tests could be simplified so I did this. But it's fair enough you don't want to add a dependency by importing flake8_comprehensions. Hence I said, if you want to reject, it's ok :)
2. extracting suffixes was just to be able to import in the tests, although I think that bit of the code now looks better. But that's my personal opinion.
3. for functools.reduce, what I did was to build the fully qualified name of the Function call.
`functools.reduce(...)` is represented as `Call(Attribute(Name('functools'), 'reduce'), ...)`.
4. Regarding false positive with people redefining `reduce`, the same happens for all other symbols. e.g. there are python builtins called `id` and `input` and those are very common variable names.
5. It would be possible to detect a `Import([alias('functools',...)])` or `ImportFrom('functools', [alias('reduce',...)])` to build a table with imported symbols. That would have the benefit of allowing to extend the checker to `itertools.*`. Might be a fun exercise if you think it's worth while.

**Comment by adamchainz** [comment]
On #5 yes that would help

On #6 yes but it's a lot of work with module and function scopes. If there's a helper out there to deal with it. Ultimately it would be more useful if flake8 didn't just give us the AST to check, but called us as another visitor whilst walking the tree, and gave us not only the current symbol but some state such as in-scope imports.

**Comment by joaoe** [comment]
Regarding windows, the only problem was the ./example.py bits with the forward slashes. Everything else works as expected.

**Pull request closed without merging**
