### PR TITLE
Add testing and trove classifiers for additional Python versions

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Comment by adamchainz** [comment]
Why test on Python 3.5 and 3.4? Are there incompatibilities you've found?

**Comment by jdufresne** [comment]
> Why test on Python 3.5 and 3.4? Are there incompatibilities you've found?

I started investigating if this would be a good fit for Django in PR django/django#8432. When I investigate the usefulness of a library, I check what Python versions it is documented as supporting and tested against so I can be confident it is in line with my intended use. As Django still supports Python 3.4, I wanted to see if `flake8-comprehensions` did as well. As all tests pass, I figured I'd add it to the list for others investigating the same.

**Comment by jdufresne** [comment]
Rebased to resolve merge conflicts.

**Comment by jdufresne** [comment]
> Also there are no incompatibilities with Python 3.4 and 3.5 being fixed so it's not really fixing any problems (at the moment).

By running CI testing against all supported versions we help provide confidence that bugs and regressions are not being introduced as the code changes over time. That is my goal by including this.

> I'm gonna research it a bit more and see if there's an easier way of doing it without using the matrix

Unfortunately, this is to workaround Travis combined with tox. I haven't found a better solution. The Travis Python 3.6 image does not contain Python 3.5 and the Python 3.5 image does not contain Python 3.6. Therefore, to allow tox to test all versions, some amount of the matrix is required. As I'm adding it for these two versions, I figured might as well add it for all versions. See Travis threads https://github.com/travis-ci/travis-ci/issues/4990 (looks like you've already contributed there) and https://github.com/travis-ci/travis-ci/issues/7146.

**Comment by jdufresne** [comment]
If you'd like, I could add a comment above the matrix that describes why it is being used instead of the old version. What do you think?

**Pull request closed without merging**
